### ISSUE TITLE
prometheus_scrape_port allocated to worker not used in prometheus target

### ISSUE THREAD

**Issue by hreidar** [distribrewed/stack#1]
queue_1       | /usr/local/lib/python3.6/site-packages/distribrewed_core/base/master.py:53: [INFO] Registering 'testdude' ; Info : {"events": ["on_start", "on_stop", "on_pause", "on_resume", "on_finished", "on_temperature_reached"], "id": "testdude", "info": {"is_paused": false, "is_running": false, "schedule_id": null}, "inheritance_chain": ["TemperatureWorker", "DeviceWorker", "ScheduleWorker", "BaseWorker"], "ip": "192.168.1.106", "prometheus_scrape_port": 34171, "type": "TemperatureWorker"} ; Methods : {"add_devices": [], "de_register": [], "duration_str_to_delta": ["str"], "pause_worker": [], "ping_master": [], "register": [], "resume_worker": [], "start_worker": ["schedule_id", "worker_schedule"], "stop_worker": [], "time_sync": [], "worker_info": []}
queue_1       | /opt/project/distribrewed/workers/signals.py:34: [INFO] Updating worker 'testdude' in database
consul_1      |     2017/10/12 23:32:16 [INFO] agent: Synced service 'testdude'
consul_1      |     2017/10/12 23:32:16 [DEBUG] agent: Node info in sync
consul_1      |     2017/10/12 23:32:16 [DEBUG] http: Request PUT /v1/agent/service/register (3.36684ms) from=172.18.0.6:39308
consul_1      |     2017/10/12 23:32:16 [DEBUG] agent: Service 'testdude' in sync
consul_1      |     2017/10/12 23:32:16 [DEBUG] agent: Node info in sync
consul_1      |     2017/10/12 23:32:16 [DEBUG] agent: Service 'testdude' in sync
consul_1      |     2017/10/12 23:32:16 [DEBUG] agent: Node info in sync
queue_1       | /usr/local/lib/python3.6/site-packages/distribrewed_core/base/master.py:72: [INFO] Sending ping to 'testdude'
consul_1      |     2017/10/12 23:32:16 [DEBUG] http: Request GET /v1/health/service/workers?index=6&passing=1&stale=&wait=60000ms (26.072774167s) from=172.18.0.7:36428
prometheus_1  | time="2017-10-12T23:32:16Z" level=warning msg="Received SIGTERM, exiting gracefully..." source="main.go:234" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="See you next time!" source="main.go:241" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Stopping target manager..." source="targetmanager.go:77" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Stopping rule manager..." source="manager.go:388" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Rule manager stopped." source="manager.go:394" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Stopping notification handler..." source="notifier.go:418" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Stopping local storage..." source="storage.go:457" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Stopping maintenance loop..." source="storage.go:459" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Maintenance loop stopped." source="storage.go:1458" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Stopping series quarantining..." source="storage.go:463" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Series quarantining stopped." source="storage.go:1907" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Stopping chunk eviction..." source="storage.go:467" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Chunk eviction stopped." source="storage.go:1153" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:633" 
rabbitmq_1    | 
rabbitmq_1    | =INFO REPORT==== 12-Oct-2017::23:32:16 ===
rabbitmq_1    | accepting AMQP connection <0.686.0> (172.18.0.6:43252 -> 172.18.0.2:5672)
rabbitmq_1    | 
rabbitmq_1    | =INFO REPORT==== 12-Oct-2017::23:32:16 ===
rabbitmq_1    | connection <0.686.0> (172.18.0.6:43252 -> 172.18.0.2:5672): user 'distribrewed' authenticated and granted access to vhost 'celery.distribrewed'
queue_1       | /usr/local/lib/python3.6/site-packages/distribrewed_core/base/master.py:80: [INFO] Received pong from 'testdude'
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Done checkpointing in-memory metrics and chunks in 69.189906ms." source="persistence.go:665" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Checkpointing fingerprint mappings..." source="persistence.go:1526" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Done checkpointing fingerprint mappings in 19.770512ms." source="persistence.go:1549" 
prometheus_1  | time="2017-10-12T23:32:16Z" level=info msg="Local storage stopped." source="storage.go:484" 
prometheus_1  | time="2017-10-12T23:32:17Z" level=info msg="Starting prometheus (version=1.7.2, branch=HEAD, revision=22eadbe635528fa17b99a7635fed6b6018103042)" source="main.go:88" 
prometheus_1  | time="2017-10-12T23:32:17Z" level=info msg="Build context (go=go1.8.3, user=root@05b1548df2cc, date=20170926-16:41:43)" source="main.go:89" 
prometheus_1  | time="2017-10-12T23:32:17Z" level=info msg="Host details (Linux 4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 x86_64 1e3d3c74ac6c (none))" source="main.go:90" 
prometheus_1  | time="2017-10-12T23:32:17Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:252" 
prometheus_1  | time="2017-10-12T23:32:17Z" level=info msg="Loading series map and head chunks..." source="storage.go:428" 
prometheus_1  | time="2017-10-12T23:32:17Z" level=info msg="595 series loaded." source="storage.go:439" 
prometheus_1  | time="2017-10-12T23:32:17Z" level=info msg="Starting target manager..." source="targetmanager.go:63" 
prometheus_1  | time="2017-10-12T23:32:17Z" level=info msg="Listening on :9090" source="web.go:259"

**Comment by hreidar** [comment]
@gbbirkisson any idea?

**Comment by distribrewed** [comment]
Not sure what it is. But to make things a little less complicated, the stack now runs in host mode.

Update by doing:
```
docker-compose down
git pull origin master
sudo rm -rf data
docker-compose pull
docker-compose up -d
```

Then start the worker on the raspberry pi like so:

```
docker pull distribrewed/workers:arm

docker run -d --rm --net=host --name=debug_worker \
	-e WORKER_NAME=debug_worker \
	-e AMQP_HOST=1.2.3.4 \
	-e WORKER_PLUGIN_CLASS=DebugTemperatureWorker \
	-e MASH_NAME=ssr \
	-e MASH_IO=dummy \
	-e THERMOMETER_ACTIVE=False \
	-e THERMOMETER_CYCLE_TIME=3 \
	-e PYTHONUNBUFFERED=1 \
	-e THERMOMETER_IO=dummy \
	-e MASH_CYCLE_TIME=10 \
	-e MASH_ACTIVE=False \
	-e THERMOMETER_NAME=temperature \
	distribrewed/workers:arm

docker logs debug_worker -f # To view logs
```
Where `AMQP_HOST=1.2.3.4` is the IP of the master

**Comment by gbbirkisson** [comment]
Found issue when adding workers to Consul, fixed in commit https://github.com/distribrewed/master/commit/e8642e0a46a602aab98be4a8d15600910dff2b4b
